In [1]:
import pandas as pd # Pre-requisite to run Pandas
from pandas import Series, DataFrame
import numpy as np # Pre-requisite to run numpy

In [2]:
xlsx_name = "LPICapital_Insurance" # output file name

In [3]:
# Read Benchmark (Hand-calculation Output)
benchmark = pd.read_excel("Bursa_financialServices_benchmark_cleaned.xlsx", "Sheet1", index_col = 0)
benchmark

,Financial Ratios,2020,2019,2018,2017,2016
0,Price to Book,8.126068,7.228567,6.839563,6.653040,5.895812
1,Price to Earnings,17.736739,25.849608,23.849376,23.456946,23.191438
2,Return on Equity,0.419348,0.249168,0.259862,0.266922,0.228417
3,Return on Capital Employed,0.546180,0.324321,0.336581,0.342155,0.294910
4,EBITDA to Revenue Ratio,0.678694,0.577077,0.631922,0.632505,0.623677
5,EBITDA to Cash Conversion,0.789371,0.673565,0.648027,0.743772,0.684930
6,Revenue to Expense Ratio,1.947835,1.643426,1.759434,1.724043,1.688876
7,Current Ratio,1.202994,1.211251,1.201852,1.250207,1.262987
8,Cash Ratio,0.124348,0.121174,0.110692,0.186660,0.140931
9,Operating Cash Flow Ratio,0.181070,0.121917,0.141224,0.184760,0.132951
10,Cash Conversion Ratio,1.104544,0.984543,0.929211,1.066887,0.996388
11,Debt Ratio,0.000000,0.000000,0.000000,0.000000,0.000000
12,Debt to Equity Ratio,0.000000,0.000000,0.000000,0.000000,0.000000
13,Interest Coverage Ratio,982.472119,518.867041,619.249064,617.229907,0.000000
14,Years to Repay Debt,0.000000,0.000000,0.000000,0.000000,0.000000
15,Average Interest Rate,0.000000,0.000000,0.000000,0.000000,0.000000
16,Dividend Yield,0.061446,0.034154,0.049123,0.052889,0.038305
17,Dividend Coverage Ratio,0.917559,1.132661,0.853571,0.806054,1.125682
18,Dividend Payout Ratio,1.089848,0.882877,1.171548,1.240612,0.888350

In [4]:
# Read Comparison (Code Output)
comparison =  pd.read_excel("FA_Bursa_FinancialServices.xlsx", "output", index_col = 0)
comparison

,Financial Ratios,2020,2019,2018,2017,2016
0,Price to Book,8.126068,7.228567,6.839563,6.653040,5.895812
1,Price to Earnings,17.736739,25.849608,23.849376,23.456946,23.191438
2,Return on Equity,0.419348,0.249168,0.259862,0.266922,0.228417
3,Return on Capital Employed,0.546180,0.324321,0.336581,0.342155,0.294910
4,EBITDA to Revenue Ratio,0.678694,0.577077,0.631922,0.632505,0.623677
5,EBITDA to Cash Conversion,0.789371,0.673565,0.648027,0.743772,0.684930
6,Revenue to Expense Ratio,1.947835,1.643426,1.759434,1.724043,1.688876
7,Current Ratio,1.202994,1.211251,1.201852,1.250207,1.262987
8,Cash Ratio,0.124348,0.121174,0.110692,0.186660,0.140931
9,Operating Cash Flow Ratio,0.181070,0.121917,0.141224,0.184760,0.132951
10,Cash Conversion Ratio,1.104544,0.984543,0.929211,1.066887,0.996388
11,Debt Ratio,0.000000,0.000000,0.000000,0.000000,0.000000
12,Debt to Equity Ratio,0.000000,0.000000,0.000000,0.000000,0.000000
13,Interest Coverage Ratio,982.472119,518.867041,619.249064,617.229907,0.000000
14,Years to Repay Debt,0.000000,0.000000,0.000000,0.000000,0.000000
15,Average Interest Rate,0.000000,0.000000,0.000000,0.000000,0.000000
16,Dividend Yield,0.061446,0.034154,0.049123,0.052889,0.038305
17,Dividend Coverage Ratio,0.917559,1.132661,0.853571,0.806054,1.125682
18,Dividend Payout Ratio,1.089848,0.882877,1.171548,1.240612,0.888350

In [5]:
deviation = pd.DataFrame({benchmark.columns[0]: benchmark[benchmark.columns[0]]}) # Initialize DataFrame
deviation

              Financial Ratios
0                Price to Book
1            Price to Earnings
2             Return on Equity
3   Return on Capital Employed
4      EBITDA to Revenue Ratio
5    EBITDA to Cash Conversion
6     Revenue to Expense Ratio
7                Current Ratio
8                   Cash Ratio
9    Operating Cash Flow Ratio
10       Cash Conversion Ratio
11                  Debt Ratio
12        Debt to Equity Ratio
13     Interest Coverage Ratio
14         Years to Repay Debt
15       Average Interest Rate
16              Dividend Yield
17     Dividend Coverage Ratio
18       Dividend Payout Ratio

In [6]:
for index, row in benchmark.iterrows():    
    benchmark_Values = ((benchmark.loc[benchmark[benchmark.columns[0]] == row.values[0]]).values[0])[1:] # Select only the values
    comparison_Values = ((comparison.loc[comparison[comparison.columns[0]] == row.values[0]]).values[0])[1:]
    
    #print("benchmark_Values: ", benchmark_Values)
    #print("comparison_Values: ", comparison_Values)
    
    if all(benchmark_Values):
        #print("Cond 1")
        deviation_Values = (benchmark_Values - comparison_Values)/benchmark_Values
    else:
        #print("Cond 2")
        deviation_Values = [0, 0, 0, 0, 0]
    
    #print(deviation_Values)
    
    for index, element in enumerate(list(benchmark.columns[1:len(benchmark.columns)])):
        deviation.loc[deviation[deviation.columns[0]] == row.values[0], element] = deviation_Values[index] # Insert at row and column deviation value

deviation

,Financial Ratios,2020,2019,2018,2017,2016
0,Price to Book,4.179106e-10,-1.857145e-10,-3.127272e-10,0.0,-6.170211e-10
1,Price to Earnings,4.179100e-10,-1.857142e-10,-3.127273e-10,0.0,-6.170212e-10
2,Return on Equity,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00
3,Return on Capital Employed,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00
4,EBITDA to Revenue Ratio,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00
5,EBITDA to Cash Conversion,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00
6,Revenue to Expense Ratio,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00
7,Current Ratio,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00
8,Cash Ratio,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00
9,Operating Cash Flow Ratio,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00
10,Cash Conversion Ratio,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00
11,Debt Ratio,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00
12,Debt to Equity Ratio,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00
13,Interest Coverage Ratio,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00
14,Years to Repay Debt,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00
15,Average Interest Rate,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00
16,Dividend Yield,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00
17,Dividend Coverage Ratio,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00
18,Dividend Payout Ratio,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00

In [7]:
deviation.to_excel(xlsx_name + "_deviations" + ".xlsx", sheet_name = 'output')